enabled = true
serverUrl = "https://card.segasb.me/"
session-key = ""
cardTtlMs = 5000
preferredAccessCode = "private"
aimeDbResolve = true
aimeDbHost = ""
aimeDbPort = 22345
aimeDbGameId = ""
aimeDbKeychip = ""
aimeDbStoreIdHex = "bc310000"
aimeDbTimeoutMs = 3000
